version: "3.8"

services:
  producer:
    build: ./producer
    image: producer
    networks: 
      - my-shared-network
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "java -jar producer-0.0.1-SNAPSHOT.jar"]

  consumer:
    build: ./consumer
    image: consumer
    networks: 
      - my-shared-network
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - rabbitmq
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "java -jar consumer-0.0.1-SNAPSHOT.jar"]

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - my-shared-network

networks: 
    my-shared-network:
